export const GET_EXPENSES = 'GET_EXPENSES';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const SET_LOADING = 'SET_LOADING';
export const EXPENSE_ERROR = 'EXPENSE_ERROR';
export const SEARCH_EXPENSES = 'SEARCH_EXPENSES';
